### ISSUE TITLE
Fix iOS build

### ISSUE THREAD

**Issue by JulianiusM** [JulianiusM/RecyclingApp#33]
Repair the iOS build.

This requires an iOS development and test setup (e.g. iPhone and Mac).

**Comment by Aryashakya** [comment]
Hi, I would like to work on this.

**Comment by JulianiusM** [comment]
Thank you for your contribution

**Comment by Aryashakya** [comment]
Hi,

Could you tag thePR #50 with the label 'hacktoberfest-accepted' or, add the ‘hacktoberfest’ topic to the repository ?
