### ISSUE TITLE
Implement feedback function

### ISSUE THREAD

**Issue by JulianiusM** [JulianiusM/RecyclingApp#34]
Implement a function to give direct feedback on aspects of the app.
This could include how clear the texts are formulated, if the pictures are representative of the thing described or if everything is up to date.

**Comment by linusschlepp** [comment]
This function/ tab could be added to the following menu: 

![Image](https://github.com/JulianiusM/RecyclingApp/assets/82322027/185bab3a-7007-409b-9ec7-db4d63fda844)
